[build]
  command = "npm ci --production=false && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  # VITE_API_BASE_URL should be set in Netlify environment variables
  # Go to: Site settings > Environment variables > Add variable
  # VITE_API_BASE_URL = "your-backend-url-here"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

